[tools]
"cargo:tauri-cli" = "2"
node = "lts"

[tasks.setup]
description = "Setup development environment"
run = "npm install"

[tasks.dev]
description = "Start the application in development mode"
run = "cargo tauri dev"
