[tools]
"cargo:tauri-cli" = "2"
node = "lts"

[tasks.setup]
description = "Setup development environment"
run = "npm install"

[tasks."dev:app"]
description = "Start the application in development mode"
run = "cargo tauri dev"

[tasks."dev:mcp"]
description = "Start the MCP server in development mode"
run = "npx @modelcontextprotocol/inspector cargo run -- mcp"
